### ISSUE TITLE
Build error when openPMD_USE_HDF5=OFF for the examples

### ISSUE THREAD

**Issue by jeanbez** [openPMD/openPMD-api#1074]
**Describe the bug**
When I tried to disable support for HDF5, the build process still looks for HDF5 and tries to link to the library for the examples.

**To Reproduce**

```bash
# in directory $HOME/src/openPMD-api
mkdir build && cd build

CC=mpicc CXX=mpicxx cmake .. -DopenPMD_USE_MPI=ON -DopenPMD_USE_ADIOS2=ON -DopenPMD_USE_HDF5=OFF -DopenPMD_USE_ADIOS1=ON -DCMAKE_CXX_STANDARD=14
```
```
Consolidate compiler generated dependencies of target 8a_benchmark_write_parallel
[ 54%] Linking CXX executable bin/8a_benchmark_write_parallel
lib/libopenPMD.so: undefined reference to `H5Dset_extent'
lib/libopenPMD.so: undefined reference to `H5Pcreate'
lib/libopenPMD.so: undefined reference to `H5Aexists'
lib/libopenPMD.so: undefined reference to `H5T_NATIVE_INT8_g'
lib/libopenPMD.so: undefined reference to `H5Tis_variable_str'
lib/libopenPMD.so: undefined reference to `H5Oopen'
lib/libopenPMD.so: undefined reference to `H5Tget_size'
lib/libopenPMD.so: undefined reference to `H5Fopen'
lib/libopenPMD.so: undefined reference to `H5T_NATIVE_INT_g'
lib/libopenPMD.so: undefined reference to `H5check_version'
lib/libopenPMD.so: undefined reference to `H5Pset_coll_metadata_write'
lib/libopenPMD.so: undefined reference to `H5Gget_info'
lib/libopenPMD.so: undefined reference to `H5Awrite'
lib/libopenPMD.so: undefined reference to `H5Aclose'
lib/libopenPMD.so: undefined reference to `H5Dget_create_plist'
lib/libopenPMD.so: undefined reference to `H5Acreate2'
lib/libopenPMD.so: undefined reference to `H5Ldelete'
lib/libopenPMD.so: undefined reference to `H5Dget_space'
lib/libopenPMD.so: undefined reference to `H5Pset_all_coll_metadata_ops'
lib/libopenPMD.so: undefined reference to `H5Pget_chunk'
lib/libopenPMD.so: undefined reference to `H5Gcreate2'
lib/libopenPMD.so: undefined reference to `H5Tget_member_name'
lib/libopenPMD.so: undefined reference to `H5Aopen'
lib/libopenPMD.so: undefined reference to `H5T_NATIVE_LLONG_g'
lib/libopenPMD.so: undefined reference to `H5Tenum_insert'
```

**Expected behavior**
If I disabled the HDF5, I would expect it not to look for the library files and build only the ADIOS support.

**Software Environment**
 - version of openPMD-api: `9170612465e2eac3ad5258e6c746b59dda64a369`
 - installed openPMD-api via: source
 - operating system: 
 - machine: Summit
 - version of HDF5: hdf5/1.10.4
 - version of ADIOS1: adios/1.13.1-py2
 - version of ADIOS2: adios2/2.7.0
 - name and version of MPI: spectrum-mpi/10.3.1.2-20200121

**Comment by ax3l** [comment]
@jeanbez, thanks for the report!
I don't control or have experience with the Summit `adios/1.13.1-py2` module and it looks quite Python-centric. (Python2 even :scream: )

Can you use `-DopenPMD_USE_ADIOS1=OFF`? ADIOS1 is fully deprecated by the developers. If you really need it we can try to build it from source with consistency between the other dependencies & compilers ensured.

Do you still see the linker problem with ADIOS1 disabled? I can compile with that slight modification (and will push a few updates to ADIOS1 compiles nonetheless.) Can you please post your modules, env vars (i.e., `CC`/`CXX` values) and CMake output otherwise?

Is it possible that your ADIOS2 was built with support for HDF5 conversion/output? Did you built it yourself or is that from my ums module in `aph114`?

Side note: there is no need to set `mpicc`/`mpicxx` as CC/CXX with CMake. Just export your `CC`/`CXX` to `$(which gcc)` and `$(which g++)` of the loaded module :) (Summit default before the upcoming update this month: GCC 6.4.0)

**Comment by ax3l** [comment]
Problem solved via Slack today:
there was an outdated `openPMD/config.hpp` file in our source tree, potentially from an earlier in-source run of CMake. This will be prevented in #1079 now :)
