### ISSUE TITLE
A Variant-Based LoadChunk

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1372]
It would be great if we can design load routines that are variant-based.

That way, the user-side logic is more concise than knowing the exact type upfront.

Similar for attribute reads (where we already support some flexible casts).

**Comment by franzpoeschel** [comment]
The logic of our `switchType` thingy is very similar to `std::visit` and can be used today already by including `DatatypeHelpers.hpp` (public header on purpose). Maybe a wrapper around this would be a solution?
Otherwise, to use `std::visit` (which would be nice as it's well-documented STL code), we would have to use an actual `std::variant` somewhere, but it's probably doable too.

**Comment by ax3l** [comment]
Things we could add:
- public std::variant for our users for our defined types
- return overloads that return a pre-allocated variant
- helpers so that users can pass us a pre-allocated `float` (`double`, etc.) pointer and we write into it, converting if needed
