### ISSUE TITLE
Particles: Support Auto-Shape Counting

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#1374]
For particles, we need to investigate how we can deine openPMD Datatyopes that have only a local size, where their global size is determined at runtime.

This currently would only work with ADIOS2 2.9+ using `JoinedArrays` and would safe users from having to do collective All2All comms (reduce sum and a scan) for particle global sizes and offsets prior to I/O.

Related to: https://github.com/ornladios/ADIOS2/issues/3452

**Comment by ax3l** [comment]
attn @guj @franzpoeschel :)

**Comment by ax3l** [comment]
As a first step, we need to define the equivalent of `adios2::JoinedDim` in openPMD-api for our dataset definitions.

Then we might need to disable a few shape checks in writing when this size is used (since it's max-size - N, this might not be needed; maybe we can also encode this as a state in the data type w/o magic constants).

**Comment by franzpoeschel** [comment]
Since this feature is relevant for basically all parallel code that writes particles, we should (as a second step) implement this also in openPMD, so that those codes still stay compatible with HDF5.
Using MPI collectives to determine local block offsets inside the particle list is a really common pattern for using openPMD in such code, and this is a great chance to eliminate this pattern, while still staying compatible with all openPMD backends.

**Comment by ax3l** [comment]
ADIOS2 now implements in the `master` (upcoming `2.9` release) JoinedArrays in both BP4 and BP5.
https://github.com/ornladios/ADIOS2/issues/3452#issuecomment-1437499120

As a first step, we need to support this in the shape of our `openPMD::Dataset` definition and add support to our ADIOS2 backend.

**Comment by franzpoeschel** [comment]
A challenge will be the support for particle patches. 
Does ADIOS2 give a guarantee that the joined order of chunks is determined deterministically from the order in which IO operations are enqueued (even in parallel)?
