### ISSUE TITLE
Integration tests as mandatory phase in CI

### ISSUE THREAD

**Issue by anokfireball** [openPMD/openPMD-api#195]
To detect problems like #187 early, integration tests that verify this API's output should be a mandatory step for CI to pass. Ideally, these tests run in isolation from the API to provide certain objectivity.

Potential candidates include
 - [openPMD-validator](https://github.com/openPMD/openPMD-validator) for [openPMD-standard](https://github.com/openPMD/openPMD-standard)-compliance
 - h5py tests as described in #50

**Comment by ax3l** [comment]
Yes, probably in a later step. I try not to "pollute" the install with too much other packages like `h5py` until everything is installed. Probably we need to move the travis `script` section to `before_script` and then add such additional software and tests in `script` ([because later sections are not causing a build to fail](https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build))
