### ISSUE TITLE
Documentation: include how to compile the C++ Examples

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-api#502]
I found the [examples](https://github.com/openPMD/openPMD-api/tree/dev/examples) very instructive.

However, as someone who knows almost nothing besides Python (shame on me!), it is unclear how to compile/test the examples. Having installed openpmd-api (from source+cmake) in `/usr/local/`, my naive attempt was:
```
g++ -I/usr/local/include/ -L/user/local/lib/ -lopenPMD 2_read_serial.cpp 
```

Could you add the correct command in the documentation?

**Comment by ax3l** [comment]
Thanks for the feedback!

So far we have the [linking to your project](https://github.com/openPMD/openPMD-api#linking-to-your-project) section in the `README.md` which recommends using CMake downstream.

If you want to link manually, you probably have to add a few defines such as `-DopenPMD_USE_MPI=ON` in case you added support for it at runtime. (We can add an old-style `pkg-config`/`.pc` file for this to assist.)

What kind of error did you get with the command above? Your command would be correct for a `shared` lib.

In case you installed openPMD-api statically, the compiler just adds the `static` lib like any other source file:
```
g++ -I/usr/local/include/ 2_read_serial.cpp /user/local/lib/libopenPMD.a
```

What's the install method you used and which version of openPMD-api did you install?

**Comment by RemiLehe** [comment]
Thanks for the quick answer!

Recommending CMake definitely makes sense ; however, for my particular use case, this is not an option.

You were right: I had built the openPMD library statically (using CMake here). So, in the end, the following command did the trick:
```
g++ -I/usr/local/include/ -std=c++11 -lhdf5 3_write_serial.cpp /usr/local/lib/libopenPMD.a 
```

**Comment by ax3l** [comment]
Yes, that makes sense.

Manual linking is not really comfortable, since I/O dependency stacks are long and deep.

We can reduce that burden a little for manual linking by also installing a `.pc` file. With its help, manual building would look something like:

```bash
g++ 3_write_serial.cpp $(pkg-config --libs --cflags openPMD-api)
```

as long as the environment variable `PKG_CONFIG_PATH` is properly expanded and you have the `pkg-config` tool on the system (most unix do).

It's a bit painful to create them with all the corner cases (such as with/without rpaths) and transient dependencies, but if it helps we can try that.

**Comment by ax3l** [comment]
Implemented `.pc` file helpers in #532 #535 #580
