### ISSUE TITLE
Extensible datasets / Flexible Extent until Close

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-api#510]
Does the openPMD-api support extensible datasets?
(e.g. dataset that can be resized with [H5Dset_extent](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-SetExtent))

A typical example would be in order to write the properties of all the particles that cross a given plane, thoughout a simulation: 
in this case we do not know the number of particles that we need to write in advance, but we can resize the dataset every time that we need to dump this particle data. (in principle at every iteration, but in practice, this data can be cashed in RAM for several iterations, so that we only need to resize datasets and dump data to disk at every ~10 or ~100 iterations).

The above example is closely related to writing the particle in the lab frame, during a boosted-frame simulation, which is what I am really interested in, in the end :)

**Comment by ax3l** [comment]
Not yet, but it can be enabled for some backends such HDF5 and ADIOS1/2.

Nevertheless, please be  aware that extensible datasets are horrible in performance in HDF5. We have done benchmarks with libSplash in the past (of course, we forgot to post the numbers, argh) and I would not use them for anything serious: https://github.com/ComputationalRadiationPhysics/libSplash/issues/133 https://github.com/ComputationalRadiationPhysics/libSplash/pull/135

If your workflow allows, avoid `H5F_UNLIMITED` at all costs (also plays into the nightmare of chunking in H5 #406), which will make your I/O faster and your choice of backends more flexible. I know it's unfortunate, but HDF5 today do not implement resizing/appending in an efficient way at scale.

In ADIOS(1/2), "extent" of a dataset is a more of loose meta concept and one could just write more and more chunks and store the final size in a variable. There it should work well already, but one should check. We probably should expose this "flexible" extent then in the frontend as well, otherwise the read API might crop the extent on what you initially gave it.

Those are not the latest slides from a few weeks ago, but from 2016. Still, the tutorial contains bounding boxes: https://users.nccs.gov/~pnorbert/adios-tutorial.pdf in p. 69+. We should be able to expose them that way :)

I personally would address such a task with chunks in openPMD-api and probably also the upcoming streaming API by @franzpoeschel, but it works regularly as well. Maybe we can add such a workflow as an example!

**Comment by RemiLehe** [comment]
Thanks a lot for the above comments and advice! This makes a lot of sense!

I agree that resizable datasets should be avoided whenever possible. However, there are cases in which they seem (to me) to be hard to avoid.

Imagine for example the following case: a user of a given PIC code wants a plugin that records all the electrons that go through the rear-plane of a solid foil, in a 3D TNSA simulation. (i.e. the amount of data will be very large - and is progressively collected, at each iteration, throughout the simulation) In that case, we do not know in advance how many particles will go through that plane. Also, from your above remark, it looks like ADIOS could handle by this writing several chunks before finally dumping them to disk. However, if I understand correctly, these chunks are stored in RAM - which would not be practical for the above TNSA example (data might exceed the size of the RAM).

Is there a way to handle the above hypothetical TNSA example without resizable datasets?

**Comment by ax3l** [comment]
> I agree that resizable datasets should be avoided whenever possible.

Maybe I expressed this a bit mixed above and edited the initial post to heavily. One should avoid `H5F_UNLIMITED` (HDF5 resizable datasets) just for performance and implementation complexity reasons, but for HDF5 that is the only way to do this.

> ADIOS could handle by this writing several chunks before finally dumping them to disk. However, if I understand correctly, these chunks are stored in RAM.

Not necessarily, the amount of RAM used for buffering can be controlled and will start writing when its full, so one can avoid running out of memory. So as a user it's really just "new particles - new chunk - flush" while keeping the record and series open.

> Imagine for example the following case ... we do not know in advance how many particles will go through that plane ... Is there a way to handle the above hypothetical TNSA example without resizable datasets?

Absolutely, I think for all such tracking-kind of workflows this is needed and possible, but we have to expose/implement a flexible record extent as a feature first (and it will likely not work well with all backends, but that's ok).

**Comment by RemiLehe** [comment]
OK, thanks! 
If you do implement a feature for flexible record extent in openPMD-api, I would definitely use it :)
Should I close this issue?

**Comment by ax3l** [comment]
Here as well :)
Keep it open, so we can assign and update it when implementation work starts.
