### ISSUE TITLE
spack install with gcc@>=9 fails because of a bug nlohmann/json (fixed for >3.5)

### ISSUE THREAD

**Issue by hightower8083** [openPMD/openPMD-api#555]
```spack install openpmd-api %gcc@9.2.0```
 fails at installing `nlohmann/json` with [this](https://github.com/nlohmann/json/issues/1472). 

This issue of json with gcc@>=9 was [fixed](https://github.com/nlohmann/json/pull/1492#event-2194072920), but spack's preferred version is 3.5. 
When I manually set `nlohmann-json` version to 3.7, installation succeeds.

**Comment by ax3l** [comment]
Thank you for the detailed report and testing the new GCC compiler!
In your linked PR, this seams to be fixed in nlohmann-json 3.6 and newer. The problem only occurs while building its tests, which also is non-default in spack.

The following fixes address this:
- [x] spack package of `nlohmann-json`: https://github.com/spack/spack/pull/12517 https://github.com/spack/spack/pull/12546
  - add newest release 3.7.0
  - proper test handling to save compile time unless requested via `spack install -v --test root nlohmann-json`
- [x] openPMD-api: increase internal dependency to 3.7.0+ https://github.com/openPMD/openPMD-api/pull/556

**Comment by hightower8083** [comment]
yeah, i had a nasty experience of playing with `update-initramfs -d` (`-c`) after kernel-update in ubuntu screwed nvidia's xorg -- decided to make a fresh start with a new system, drivers and compilers 😁

**Comment by ax3l** [comment]
Excellent choice :D Don't forget to compile with `-mtune=native -march=native` while rebuilding everything for speed ;)
All PRs are merged now. Please update your spack sources to see it in effect and feel free to close the issue if this solves it :)

**Comment by hightower8083** [comment]
checked 👌

**Comment by hightower8083** [comment]
by the way, @ax3l, in which context you suggest to use the flags exactly? Consider I have `gcc@9.2.0` built by spack (using default ubuntu's `gcc@7.4.0`), should I simply add 
```
    flags:   
      cppflags: -mtune=native -march=native
      cflags: -mtune=native -march=native
```
to 9.2.0 part in `.spack/linux/compilers.yaml`? 
Will it apply such optimization to everything built with `gcc@9.2.0` even outside spack (like if I do warpx from source) ? Or should I add 
```
export CFLAGS="-mtune=native -march=native"
export CPPFLAGS="-mtune=native -march=native"
```
to my `.bashrc`?

**Comment by ax3l** [comment]
Just joking a little, these flags will cause compiled binaries to be optimally tuned for the current platform it's compiling on. But you won't notice much on regular desktop applications. Adding those to spack's `compilers.yaml` only influences packages build with spack. If you compile outside of spack, use `CFLAGS` and `CXXFLAGS` (careful: `CPPFLAGS` is your pre-compiler, aka text replacements; same typo in first quote: use `cxxflags` instead). Yes, you can generally add this to `.bashrc` if you like, I usually add those manually during compile.
