### ISSUE TITLE
Internally Use optional-lite

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#563]
@franzpoeschel would like to use a preview of `std::optional` internally (without crossing the public API).

We could use [optional-lite](https://github.com/martinmoene/optional-lite) this in C++11.

Originally mentioned in
https://github.com/openPMD/openPMD-api/pull/482#discussion_r331526730

**Comment by franzpoeschel** [comment]
Alternatively, we already have a backport of `std::variant` in the openPMD API which can be used to quickly implement an `optional` type. 
Since I needed this on my streaming branch, I did just that in [a recent commit](https://github.com/franzpoeschel/openPMD-api/commit/74f37a8bbd8a6922955f0fc793bbc7ee80365e30).

**Comment by ax3l** [comment]
Sounds good, feel free to expose it as a separate header object in a PR already.
