### ISSUE TITLE
Scalar Mesh shares all attributes with its MeshRecordComponent

### ISSUE THREAD

**Issue by pordyna** [openPMD/openPMD-api#964]
**Describe the bug**
I'm not sure if this is really a bug or if it is like that by design but I found it confusing. So when I access attributes of a scalar valued mesh I get not only the usual mesh attributes like `gridSpacing` but also `MeshRecordComponent` attributes like `position`. The same happens when I access record's attributes.

```python
import openpmd_api as io
import numpy as np

new_series= io.Series('series.json', io.Access_Type.create)
data = np.arange(10)
iteration = new_series.iterations[0]
mesh = iteration.meshes['Mesh']
mrc = mesh[io.Mesh_Record_Component.SCALAR]
dataset = io.Dataset(
    data.dtype,
   data.shape)
mrc.reset_dataset(dataset)
mrc.store_chunk(data)
new_series.flush()
del new_series
new_series= io.Series('series.json', io.Access_Type.read_only)
iteration = new_series.iterations[0]
mesh = iteration.meshes['Mesh']
mrc = mesh[io.Mesh_Record_Component.SCALAR]
print(mrc.attributes)
print(mesh.attributes)
```
will output:
```
['axisLabels', 'dataOrder', 'geometry', 'gridGlobalOffset', 'gridSpacing', 'gridUnitSI', 'position', 'timeOffset', 'unitDimension', 'unitSI']
['axisLabels', 'dataOrder', 'geometry', 'gridGlobalOffset', 'gridSpacing', 'gridUnitSI', 'position', 'timeOffset', 'unitDimension', 'unitSI']
```

It does it with ADIOS, HDF5 and JSON. 

**Expected behavior**
If possible list only the mesh, mrc specific  attributes like with vector fields.

**Software Environment**
 - version of openPMD-api: 0.13.2
 - installed openPMD-api via: conda-forge, from source
 - machine: hemera

**Comment by ax3l** [comment]
Thanks for the question and detailed example!

I think this (extra) behavior is not needed but ok, since a scalar mesh only contains one entry and thus the additional information on the mesh itself that only applies for an individual component is not wrong. This is in fact reflecting a compactness feature that we are define in the standard for scalar records and if it wouldn't be so confusing, I would even had skipped the `[SCALAR]` sub-access in the API design.

Note that we provide Python properties for the standard-defined attributes as well, they are always on the right place (component or record, respectively). Furthermore, I forwarded a few record properties to the component recently too, since that makes passing a record component without its record to functions easier.

**Comment by pordyna** [comment]
It sure make sense for a scalar field to not have components. So this is probably really not needed. 
So I'm writing some code that will allow me to read an `SST` series in streaming mode, reduce resolution of the fields stored in meshes and write it to a new file based series. The idea is to use it with `PIConGPU` and write output in reduced resolution. I want to preserve all the attributes so i just copy everything in `.attributes` for all attributables. But I have to to set the new `gridSpacing`. So I just need to make sure that I set it  after I copy mesh __and__ record component attributes. Otherwise I would probably overwrite the new spacing with the old one for scalar fields. 

But yeah, this is not exactly a standard usage case :sweat_smile:

**Comment by ax3l** [comment]
Sounds great! You probably coordiante with @franzpoeschel already, but make sure you are aware of the new `openpmd-pipe` tool #904 for such workflows :)

(Docs are still to-do for the 0.14 release for it: https://openpmd-api.readthedocs.io/en/latest/utilities/cli.html)
