### ISSUE TITLE
Wrong arguments to `setGridSpacing` (and others) not properly diagnosed

### ISSUE THREAD

**Issue by eschnett** [openPMD/openPMD-api#990]
I received this error when building my application:
```
/home/eschnetter/src/CarpetX/Cactus/configs/sim/lib/libthorn_CarpetX.a(io_openpmd.cxx.o): In function `CarpetX::carpetx_openpmd_t::OutputOpenPMD(_cGH const*, std::vector<bool, std::allocator<bool> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
io_openpmd.cxx:(.text+0xeec): undefined reference to `openPMD::Mesh& openPMD::Mesh::setGridSpacing<unsigned long>(std::vector<unsigned long, std::allocator<unsigned long> > const&)'
```

The reason is that I accidentally passed a `vector<unsigned long>` with the grid spacing. The C++ header files accept this, but apparently the respective template instantiation is missing.

Could this be diagnosed better? For example, the C++ headers files could could check that the template argument of `setGridSpacing` is one of the supported arguments. [`std::is_floating_point`](https://en.cppreference.com/w/cpp/types/is_floating_point) would be handy for this.

The same problem exists for a few other functions as well.

**Comment by ax3l** [comment]
Ouch, we successfully transformed a compile-time or at least runtime check into a linker error. Fully agree.

If we think that's useful, we could also cast if these attributes are passed as non-floats. Just because we will store some attributes as `floats` does not mean we need to reject them in the API... (Unless we find the cast to be too implicit in behavior.)
